---
- name: Меняем имя машины
  shell: "echo {{ inventory_hostname }} > /etc/hostname"
  when: "inventory_hostname != ansible_hostname"

- name: Установка программ
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages_to_install }}"
  when: ansible_distribution == "Debian"

